obj-y += telnetd/
obj-y += dhcpc/
obj-y += resolv/
obj-y += smtp/
obj-y += webserver/
obj-y += webclient/
obj-y += hello-world/

obj-y += $(patsubst %.c,%.o,$(wildcard *.c))
obj-y += $(patsubst %.s,%.o,$(wildcard *.s))